[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
               test_*_*.py

testpaths =
    api/tests
    users/tests
    ads/tests

norecursedirs =
    __pycache__
    .pytest_cache
    .venv