[pytest]
# Конфигурация pytest для Django проекта

# Основные настройки:
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
               test_*_*.py

# Пути к директориям с тестами:
testpaths =
    api/tests
    users/tests
    ads/tests

# Директории, которые pytest должен игнорировать:
norecursedirs =
    __pycache__
    .pytest_cache
    .venv