# Generated by Django 5.2.1 on 2025-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ads/images/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Электроника"),
                            ("clothing", "Одежда"),
                            ("books", "Книги"),
                            ("furniture", "Мебель"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "Новое"), ("used", "Б/у")],
                        max_length=50,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(max_length=500, verbose_name="Комментарий"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение обмена",
                "verbose_name_plural": "Предложения обмена",
                "ordering": ["-created_at"],
            },
        ),
    ]
