# Generated by Django 5.2.1 on 2025-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_options_alter_ad_author_alter_ad_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/images/", verbose_name="Фото"
            ),
        ),
    ]
