# Generated by Django 5.2.1 on 2025-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
    ]
