# Generated by Django 5.2.1 on 2025-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/", verbose_name="Фото"
            ),
        ),
    ]
