# Generated by Django 5.2.1 on 2025-05-26 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_ad_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="exchange_completed",
            field=models.BooleanField(default=False, verbose_name="Обмен завершен"),
        ),
        migrations.AddField(
            model_name="ad",
            name="exchange_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_exchanges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обмен с пользователем",
            ),
        ),
    ]
