# Generated by Django 5.2.1 on 2025-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_alter_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(max_length=200, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Заголовок"),
        ),
    ]
