# Generated by Django 5.2.1 on 2025-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_alter_ad_description_alter_ad_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
